// App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, computed } from 'vue';
import { GameState, CircleDefinition, PlayerClick, Score } from './types';
import { generateSequence, calculateScore, calculateFrequencyFromY } from './services/gameLogic';
import {
  initAudio,
  playTone,
  playSoundEffect,
  startPlayerTone,
  stopPlayerTone,
  updatePlayerTonePitch,
  loadBackgroundMusic,
  startBackgroundMusic,
  onNextLoop,
  setBackgroundMusicVolume,
} from './services/audioService';
import {
  ANIMATION_DURATION_MS,
  MAX_POSITION_ERROR_PX,
  MAX_RHYTHM_ERROR_MS,
} from './constants';
import GameCanvas from './components/GameCanvas.vue';
import UIOverlay from './components/UIOverlay.vue';
import { backgroundMusicBase64Encoded } from './sounds';

const gameState = ref<GameState>(GameState.Idle);
const sequence = ref<CircleDefinition[]>([]);
const playerClicks = ref<PlayerClick[]>([]);
const score = ref<Score | null>(null);
const round = ref<number>(1);
const activePlaybackIndex = ref<number | null>(null);
const audioReady = ref<boolean>(false);
const isMusicSetup = ref<boolean>(false);
const isMuted = ref<boolean>(false);
const dimensions = ref({ width: 0, height: 0 });

const handleCanvasReady = (newDimensions: { width: number; height: number }) => {
  dimensions.value = newDimensions;
};

const startNewRound = (targetRound: number) => {
  const sequenceLength = 2 + targetRound;
  playerClicks.value = [];
  score.value = null;
  activePlaybackIndex.value = null;
  const newSequence = generateSequence(sequenceLength, dimensions.value.width, dimensions.value.height);
  sequence.value = newSequence;
  gameState.value = GameState.Playback;
};

const handleStartGame = async () => {
  let audioIsReady = audioReady.value;
  if (!audioIsReady) {
    const success = initAudio();
    if (success) {
      audioReady.value = true;
      audioIsReady = true;
    } else {
      alert("Audio could not be initialized. The game will proceed without sound.");
    }
  }

  if (audioIsReady && !isMusicSetup.value) {
    try {
      const musicLoaded = await loadBackgroundMusic(backgroundMusicBase64Encoded);
      if (musicLoaded) {
        startBackgroundMusic();
        isMusicSetup.value = true;
      }
    } catch (e) {
      console.error("Failed to set up background music.", e);
    }
  }

  if (dimensions.value.width > 0) {
    round.value = 1;
    startNewRound(1);
  }
};

const handleNextRound = () => {
  const failed = score.value && (score.value.total < 50 || score.value.position < 30 || score.value.rhythm < 30);
  const nextRound = failed ? 1 : round.value + 1;
  round.value = nextRound;
  startNewRound(nextRound);
};

const handleToggleMute = () => {
  isMuted.value = !isMuted.value;
};

watch(isMuted, (muted) => {
  if (isMusicSetup.value) {
    setBackgroundMusicVolume(muted ? 0 : 0.3);
  }
});

watch([gameState, sequence], () => {
  if (gameState.value !== GameState.Playback || sequence.value.length === 0) return;

  let timeoutId: number;
  let isCancelled = false;

  const playNextInSequence = (index: number) => {
    if (isCancelled) return;

    if (index >= sequence.value.length) {
      gameState.value = GameState.PlayerTurn;
      activePlaybackIndex.value = null;
      return;
    }

    const circle = sequence.value[index];
    activePlaybackIndex.value = index;
    playTone(circle.frequency, ANIMATION_DURATION_MS / 1000);

    const delay = index < sequence.value.length - 1 ? sequence.value[index + 1].time - circle.time : ANIMATION_DURATION_MS * 1.5;
    timeoutId = window.setTimeout(() => playNextInSequence(index + 1), delay);
  };
  
  const startSyncedPlayback = async () => {
      await onNextLoop();
      if (isCancelled) return;

      timeoutId = window.setTimeout(() => {
          if (!isCancelled) {
              playNextInSequence(0);
          }
      }, 100);
  };

  startSyncedPlayback();

  return () => {
    isCancelled = true;
    clearTimeout(timeoutId);
  };
});

const handleInteractionStart = (click: PlayerClick) => {
  if (playerClicks.value.length < sequence.value.length) {
      const frequency = calculateFrequencyFromY(click.y, dimensions.value.height);
      startPlayerTone(frequency);
      playerClicks.value.push(click);
  }
};

const handleInteractionPitchChange = ({ y }: { y: number }) => {
    const frequency = calculateFrequencyFromY(y, dimensions.value.height);
    updatePlayerTonePitch(frequency);
};

const handleInteractionEnd = ({ x, y }: { x: number; y: number }) => {
  stopPlayerTone();
  if (playerClicks.value.length > 0) {
    const lastClickIndex = playerClicks.value.length - 1;
    const newClicks = [...playerClicks.value];
    newClicks[lastClickIndex] = { ...newClicks[lastClickIndex], x, y };
    playerClicks.value = newClicks;
  }
};

watch(playerClicks, () => {
  if (gameState.value === GameState.PlayerTurn && playerClicks.value.length === sequence.value.length && sequence.value.length > 0) {
    gameState.value = GameState.Calculating;
  }
}, { deep: true });

watch(gameState, (newGameState) => {
  if (newGameState === GameState.Calculating) {
    const timer = setTimeout(() => {
      gameState.value = GameState.Scoring;
    }, 1500);
    
    const stopTimer = () => clearTimeout(timer);
    
    // This is a bit of a hack, but it's the simplest way to ensure the timer is cleaned up
    // when the component is unmounted.
    const unwatch = watch(gameState, (newState) => {
        if (newState !== GameState.Calculating) {
            stopTimer();
            unwatch();
        }
    });

  } else if (newGameState === GameState.Scoring) {
    const calculatedScore = calculateScore(sequence.value, playerClicks.value, MAX_POSITION_ERROR_PX, MAX_RHYTHM_ERROR_MS);
    score.value = calculatedScore;
    const failed = calculatedScore.total < 50 || calculatedScore.position < 30 || calculatedScore.rhythm < 30;
    if (failed) {
      playSoundEffect('level-failed');
    } else {
      playSoundEffect('level-complete');
    }
  }
});

const clicksRemaining = computed(() => {
  return sequence.value.length - playerClicks.value.length;
});
</script>

<template>
  <div class="h-screen w-screen flex items-center justify-center font-sans bg-gray-900 text-white overflow-hidden">
    <div class="relative w-full h-full">
      <GameCanvas
        @ready="handleCanvasReady"
        :gameState="gameState"
        :sequence="sequence"
        :playerClicks="playerClicks"
        :activePlaybackIndex="activePlaybackIndex"
        @playerInteractionStart="handleInteractionStart"
        @playerInteractionPitchChange="handleInteractionPitchChange"
        @playerInteractionEnd="handleInteractionEnd"
      />
      <UIOverlay
        :gameState="gameState"
        :score="score"
        :round="round"
        :clicksRemaining="clicksRemaining"
        :isMuted="isMuted"
        :isMusicSetup="isMusicSetup"
        @start="handleStartGame"
        @nextRound="handleNextRound"
        @toggleMute="handleToggleMute"
      />
    </div>
  </div>
</template>
<style>
html, body {
  overscroll-behavior-x: none;
}
</style>

// App.tsx

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { GameState, CircleDefinition, PlayerClick, Score } from './types';
import { generateSequence, calculateScore, calculateFrequencyFromY } from './services/gameLogic';
import {
  initAudio,
  playTone,
  playSoundEffect,
  startPlayerTone,
  stopPlayerTone,
  updatePlayerTonePitch,
  loadBackgroundMusic,
  startBackgroundMusic,
  onNextLoop,
  setBackgroundMusicVolume,
} from './services/audioService';
import {
  ANIMATION_DURATION_MS,
  MAX_POSITION_ERROR_PX,
  MAX_RHYTHM_ERROR_MS,
} from './constants';
import GameCanvas from './components/GameCanvas';
import UIOverlay from './components/UIOverlay';
import { backgroundMusicBase64Encoded } from './sounds';

const App: React.FC = () => {
  const [gameState, setGameState] = useState<GameState>(GameState.Idle);
  const [sequence, setSequence] = useState<CircleDefinition[]>([]);
  const [playerClicks, setPlayerClicks] = useState<PlayerClick[]>([]);
  const [score, setScore] = useState<Score | null>(null);
  const [round, setRound] = useState<number>(1);
  const [activePlaybackIndex, setActivePlaybackIndex] = useState<number | null>(null);
  const [audioReady, setAudioReady] = useState<boolean>(false);
  const [isMusicSetup, setIsMusicSetup] = useState<boolean>(false);
  const [isMuted, setIsMuted] = useState<boolean>(false);
  const [dimensions, setDimensions] = useState({ width: window.innerWidth, height: window.innerHeight });

  useEffect(() => {
    const handleResize = () => {
      setDimensions({ width: window.innerWidth, height: window.innerHeight });
    };
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const startNewRound = useCallback((targetRound: number) => {
    const sequenceLength = 2 + targetRound;
    setPlayerClicks([]);
    setScore(null);
    setActivePlaybackIndex(null);
    const newSequence = generateSequence(sequenceLength, dimensions.width, dimensions.height);
    setSequence(newSequence);
    setGameState(GameState.Playback);
  }, [dimensions.width, dimensions.height]);

  const handleStartGame = useCallback(async () => {
    let audioIsReady = audioReady;
    if (!audioIsReady) {
      const success = initAudio();
      if (success) {
        setAudioReady(true);
        audioIsReady = true;
      } else {
        alert("Audio could not be initialized. The game will proceed without sound.");
      }
    }

    if (audioIsReady && !isMusicSetup) {
      try {
        const musicLoaded = await loadBackgroundMusic(backgroundMusicBase64Encoded);
        if (musicLoaded) {
          startBackgroundMusic();
          setIsMusicSetup(true);
        }
      } catch (e) {
        console.error("Failed to set up background music.", e);
      }
    }
    
    setRound(1);
    startNewRound(1);
  }, [audioReady, isMusicSetup, startNewRound]);


  const handleNextRound = () => {
    const failed = score && (score.total < 50 || score.position < 30 || score.rhythm < 30);
    const nextRound = failed ? 1 : round + 1;
    setRound(nextRound);
    startNewRound(nextRound);
  };

  const handleToggleMute = useCallback(() => {
    setIsMuted(prev => !prev);
  }, []);

  useEffect(() => {
    if (isMusicSetup) {
        setBackgroundMusicVolume(isMuted ? 0 : 0.3);
    }
  }, [isMuted, isMusicSetup]);


  // Game state: Playback
  useEffect(() => {
    if (gameState !== GameState.Playback || sequence.length === 0) return;

    let timeoutId: number;
    let isCancelled = false;

    const playNextInSequence = (index: number) => {
      if (isCancelled) return;

      if (index >= sequence.length) {
        setGameState(GameState.PlayerTurn);
        setActivePlaybackIndex(null);
        return;
      }
      
      const circle = sequence[index];
      setActivePlaybackIndex(index);
      playTone(circle.frequency, ANIMATION_DURATION_MS / 1000);
      
      const delay = index < sequence.length - 1 ? sequence[index + 1].time - circle.time : ANIMATION_DURATION_MS * 1.5;
      timeoutId = window.setTimeout(() => playNextInSequence(index + 1), delay);
    };
    
    const startSyncedPlayback = async () => {
        // Await the next loop of the background music.
        await onNextLoop();
        if (isCancelled) return;

        // Small grace period to ensure the beat has "landed" visually/audibly.
        timeoutId = window.setTimeout(() => {
            if (!isCancelled) {
                playNextInSequence(0);
            }
        }, 100);
    };

    startSyncedPlayback();

    return () => {
      isCancelled = true;
      clearTimeout(timeoutId);
    };
  }, [gameState, sequence]);

  const handleInteractionStart = useCallback((click: PlayerClick) => {
    if (playerClicks.length < sequence.length) {
        const frequency = calculateFrequencyFromY(click.y, dimensions.height);
        startPlayerTone(frequency);
        setPlayerClicks(prev => [...prev, click]);
    }
  }, [playerClicks.length, sequence.length, dimensions.height]);

  const handleInteractionMove = useCallback(({ x, y }: { x: number, y: number }) => {
    if (playerClicks.length === 0 || playerClicks.length > sequence.length) return;
    
    setPlayerClicks(prev => {
        const updatedClicks = [...prev];
        const lastClick = updatedClicks[updatedClicks.length - 1];
        updatedClicks[updatedClicks.length - 1] = { ...lastClick, x, y };
        return updatedClicks;
    });

    const frequency = calculateFrequencyFromY(y, dimensions.height);
    updatePlayerTonePitch(frequency);

  }, [playerClicks, sequence.length, dimensions.height]);

  const handleInteractionEnd = useCallback(() => {
    stopPlayerTone();
  }, []);

  // Game state: Player turn -> Calculating
  useEffect(() => {
    if (gameState === GameState.PlayerTurn && playerClicks.length === sequence.length && sequence.length > 0) {
      setGameState(GameState.Calculating);
    }
  }, [gameState, playerClicks, sequence]);

  // Game state: Calculating -> Scoring
  useEffect(() => {
    if (gameState === GameState.Calculating) {
      const timer = setTimeout(() => {
        setGameState(GameState.Scoring);
      }, 1500); // Add a small delay for suspense

      return () => clearTimeout(timer);
    }
  }, [gameState]);

  // Game state: Scoring
  useEffect(() => {
    if (gameState === GameState.Scoring) {
      const calculatedScore = calculateScore(sequence, playerClicks, MAX_POSITION_ERROR_PX, MAX_RHYTHM_ERROR_MS);
      setScore(calculatedScore);
      const failed = calculatedScore.total < 50 || calculatedScore.position < 30 || calculatedScore.rhythm < 30;
      if (failed) {
        playSoundEffect('level-failed');
      } else {
        playSoundEffect('level-complete');
      }
    }
  }, [gameState, sequence, playerClicks]);

  const clicksRemaining = useMemo(() => {
    return sequence.length - playerClicks.length;
  }, [sequence.length, playerClicks.length]);

  return (
    <div className="h-screen w-screen flex items-center justify-center font-sans bg-gray-900 text-white">
      <div className="relative w-full h-full">
        <GameCanvas
          gameState={gameState}
          sequence={sequence}
          playerClicks={playerClicks}
          activePlaybackIndex={activePlaybackIndex}
          onPlayerInteractionStart={handleInteractionStart}
          onPlayerInteractionMove={handleInteractionMove}
          onPlayerInteractionEnd={handleInteractionEnd}
          width={dimensions.width}
          height={dimensions.height}
        />
        <UIOverlay
          gameState={gameState}
          score={score}
          round={round}
          clicksRemaining={clicksRemaining}
          isMuted={isMuted}
          isMusicSetup={isMusicSetup}
          onStart={handleStartGame}
          onNextRound={handleNextRound}
          onToggleMute={handleToggleMute}
        />
      </div>
    </div>
  );
};

export default App;
